### ISSUE TITLE
Sending to multiple sites doesn't work

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Gateway#101]
### Symptoms

When sending a message to multiple sites, only the last registered site will get the message.

### Who's affected

v3.0.0 user sending to more than one site.

**Comment by SzymonPobiega** [comment]
Looks like a low hanging fruit to be included in the scope of #100. @Particular/keeping-the-lights-on-squad I am giving a green light to the TF of #100 to also fix this one and release both.
