### ISSUE TITLE
Add support for reply address per gateway channel

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Gateway#12]
Current gateway configuration allows only for a single reply to address. When using the built-in Http channel, this address is also used for hosting the HttpListener.

When the gateway is hosted behind a load balancer, the public address of the gateway can be different from the local address on the machine hosting the actual gateway endpoint.

Having separate reply address config for each channel will decouple the HttpListener from the reply address and allow more flexibility when additional gateway channels (like SQS, ActiveMQ, Azure) are available later on.

http://tech.groups.yahoo.com/group/nservicebus/message/20000

**Comment by johnsimons** [comment]
hi @chrisbednarski,
Finally going through some old request for features on the gateway code and I come across this one raised by you.

Are you proposing to add an extra configuration settings to the `ChannelConfig` to set the return address?
Would we return this address in a http header ? Which one? 

is this it?

**Comment by chrisbednarski** [comment]
Hi @johnsimons 
Yes, this is all about an extra configuration settings on the `Channels` config section.

We currently achieve our goals by adding a dummy channel and tagging it as the default.

```
<GatewayConfig>
	<Sites>
  	</Sites>
	<Channels>
		<Channel Address="https://some.address.com/" ChannelType="Http" Default="true" />
		<Channel Address="http://+:80/" ChannelType="Http" />
	</Channels>
</GatewayConfig>
```

Load balancer passes the HTTPS traffic onto the HTTP port 80.
`Bus.Reply` uses the address from the default channel and everything falls into place.

It would be better if I didn't have to do this workaround.

**Comment by chrisbednarski** [comment]
I think it's the `Headers.OriginatingSite` and can be found [here](https://github.com/Particular/NServiceBus.Gateway/blob/develop/src/NServiceBus.Gateway/Sending/GatewaySender.cs#L93)

**Comment by chrisbednarski** [comment]
there's an old pull request https://github.com/Particular/NServiceBus/pull/1401

**Comment by johnsimons** [comment]
Thank you @chrisbednarski 

Looking at the workaround you came up with, I actually do not think is a bad one at all, which makes me wonder if we should just document it as the way to go about when behind a load balancer, thoughts? 

I looked at the https://github.com/Particular/NServiceBus/pull/1401 and there is a bit of changes just to make it work, I understand why, but I was wondering if we could instead add the `ReplyAddress` to the `SiteConfig`, I know it may feel wrong, and maybe a maintenance nightmare but just wondering, thoughts?

/cc @andreasohlund

**Comment by chrisbednarski** [comment]
Just an idea, maybe this should be re-thought altogether. Seems like a reply address is required per channel type. Would it be better to create a new config option?

```
<GatewayConfig>
    <Sites>
    </Sites>
    <Channels>
        <Channel Address="https://some.address.com/" ChannelType="Http" Default="true" />
        <Channel Address="http://+:80/" ChannelType="Http" />
        <Reply ChannelType="http" Address="https://some.address.com/" />
        <Reply ChannelType="some other channel" Address="connection string or whatever" />
    </Channels>
</GatewayConfig>
```

**Comment by johnsimons** [comment]
I'm :+1: for that
But do we add a new section? Eg `Replies`

**Comment by chrisbednarski** [comment]
Sounds good John, this can be made backwards compatible as well (if no `Replies` section exists, it falls back to the default channel, etc)

**Comment by johnsimons** [comment]
@chrisbednarski 
So now the big question, do you want to do this change?
