### ISSUE TITLE
Make IRouteMessagesToEndpoints an extension point

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.Gateway#14]
In order to support to redirect various messages to different endpoints depending on some business logic (not via namespace/assembly/type).

See original request in http://stackoverflow.com/q/30352155/90882

**Comment by janovesk** [comment]
I don't think we should support this. It's a design smell.

The gateway is designed to run per endpoint. This is some kind of mutant where the gateway for one endpoint hands off messages to multiple endpoints on the receiver side. Complicates things and makes the gateway concept more fuzzy.

Either
a) Enable the gateway for each endpoints that needs it.
b) Enable the gateway on a single endpoint, receive the message on that endpoint. If necessary, send new messages from the message handler you have there.

Thoughts, @andreasohlund and @johnsimons?

**Comment by andreasohlund** [comment]
:fire:

**Comment by johnsimons** [comment]
@janovesk my recomendation is to gather requirements from users

**Comment by janovesk** [comment]
> depending on some business logic (not via namespace/assembly/type). 
> This would allow it to fire using bus.Send(); and be configured to our requirements.

Neither of these things happen in the gateway. Reading the customers question and follow up comment on StackOverflow I'm sure the user is talking about routing messages based on business logic in NServiceBus in general, not for the gateway.

I'll update the StackOverflow post. Closing this.
