### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Gateway#19]
Connects to Particular/PlatformDevelopment#182

This is the Gateway epic which incorporates the work for making the Gateway async/await enabled. Please see [this blog post](http://particular.net/blog/async-await-its-time) about the reasoning behind it.

**Comment by janovesk** [comment]
Closed by https://github.com/Particular/NServiceBus.Gateway/pull/15, https://github.com/Particular/NServiceBus.Gateway/pull/17, https://github.com/Particular/NServiceBus.Gateway/pull/24, https://github.com/Particular/NServiceBus.Gateway/pull/25, https://github.com/Particular/NServiceBus.Gateway/pull/26, and https://github.com/Particular/NServiceBus.Gateway/pull/28
