### ISSUE TITLE
Make sure Gateway can run on multiple endpoint instances in a scale out scenario

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus.Gateway#20]
Task force: @janovesk (lead)  @szymonpobiega 

### Background
Sending messages with databus properties through the gateway is currently implemented by using one HTTP request or the message and one additional HTTP request for each databus property. The receiver correlates the calls with an in-memory cache and eventually reconstructs the message. In a scaled out scenario this will not work because physical gateway instances do not share the cache. 

Running the gateway on the master node/distributor is recommended in version 5. It is by design a single process, so this works. 

Version 6 enables non-brokered scale-out by sending messages directly to individual endpoint instances. End users will need to either

a) only enable the gateway on one particular endpoint instance and route all HTTP request to it, or 
b) enable it for all the instances and use a load balancer in front to direct the incoming HTTP traffic to one of them.

Scenario B is a highly likely deployment scenario, and the HTTP request for the message might end up on a different gateway instance than HTTP request for the individual databus properties. If that happens, none of them will have the complete message and it will be stuck in transit.

It's worth noticing that this is already broken for scaled out brokered transports in version 5, but MSMQ + gateway is presumed to be the most frequent scenario.

##### Benefits
* Very easy to implement and understand
* Nothing to correlate
* Fewer moving parts, the solution is pretty much to delete code.

##### Drawbacks
* Change from 1+N to 1 HTTP requests for a message with N databus properties. The rationale behind sending the databus properties in separate HTTP requests in the first place needs to be considered. Is it more reliable/efficient/failure tolerant to use 1+N HTTP requests instead of 1?
* Would not be backwards compatible as it can not handle version 5 messages with databus properties. No way to correlate across gateway instances.

#### 2. Return the new databus ids from the receiver
Include a new header in the response for each of the individual databus HTTP requests. The sender aggregates them and included them in the final message HTTP request.

##### Benefits
* Keep the 1+N HTTP requests for a message with N databus properties.
* Moves the correlation from receiver to the sender.

##### Drawbacks
* Slightly more complicated implementation.
* More moving parts
* Would also not be backwards compatible as it can not handle version 5 messages with databus properties. No way to correlate across gateway instances.

#### 3. Store receiver databus properties in the deduplication store
Here we can extend the deduplication store/gateway persistence to store the id of the databus properties. The gateway instances share it, so correlation works as before, just using the persisted data instead of the in-memory cache. 

##### Benefits
* Keep the 1+N HTTP requests for a message with N databus properties.
* Fully backwards compatible. Version 6 gateway can send to version 5 gateway and vice versa. 

##### Drawbacks
* The complicated implementation
* More moving parts
* The gateway persistence would need to double duty for both deduplication and correlation.

#### 4. Store metadata about the incoming gateway message in the databus store
Pretty much same as 3, but use databus store instead of deduplication store.

Here we can extend the databus store to save the id of the incoming message. The gateway instances share it, so correlation works as before, just using the persisted data instead of the in-memory cache. 

##### Benefits
* Keep the 1+N HTTP requests for a message with N databus properties.
* Fully backwards compatible. Version 6 gateway can send to version 5 gateway and vice versa. 

#### 5. Guidance
Document that the gateway is designed to run on single instance. When scaling out with the new client side solution customers should pick one of the instances to run the gatway.

##### Benefits
* Fully backwards compatible. Version 6 gateway can send to version 5 gateway and vice versa. 
* No implementation needed.
* Less moving parts.

##### Drawbacks
* All gateway requests go to a single instance. Need to make that fault resistant by using a LB in front that can detect a failing instance switch to one of the other instances instead.

### Chosen solution

5 - Guidance

Relates to https://github.com/Particular/PlatformDevelopment/issues/133
Task force is the https://github.com/Particular/PlatformDevelopment/issues/133 task force.

**Comment by ramonsmits** [comment]
@janovesk I don't understand this:

> The gateway uses an in-memory cache to correlate databus property transfers with message transfers. 

Are you referring to inbound or outbound behavior and what is the cache its purpose?

**Comment by janovesk** [comment]
Inbound, @ramonsmits. 

A message sent through the gateway is transported from the sender to the receiver as an HTTP call. If there are any databus properties in the message, the content of these is sent as separate HTTP calls. One per databus property.

We need to make sure that all databus properties has been correctly received before we can convert back to a regular message on the receiver. The gateway stores the fact that a databus property is received in an in-memory dictionary.

Works fine if all those calls go to the same physical process. In v5 this happened on the masternode, but in v6 the gateway need to run on the individual endpoint instances.

**Comment by janovesk** [comment]
Would love to hear your thoughts and alternative solutions for this @andreasohlund, @johnsimons, @ramonsmits, @SzymonPobiega and @mauroservienti.

How important it wire level compatibility between a version 5 gateway sender and a version 6 gateway receiver? The gateway is mainly intended as a component within a business service, so I would think upgrading the NServiceBus version on both ends at the same time makes sense. OTH, in the store/HQ example that is highly likely not happening at the same time.

I'm leaning against solution 3, extending the persistence store. It's the only backwards compatible solution I can see ATM.

**Comment by mauroservienti** [comment]
Ad a side note

> Version 6 enables scale-out by sending messages directly to individual endpoint instances. End users will need to either

This is not anymore true. I'll review the remaining of the issue tomorrow.

**Comment by SzymonPobiega** [comment]
@mauroservienti it still is true for MSMQ. For all the competing consumers transports the problem that @janovesk discusses here existed from the beginning of time. 

@janovesk is the fact that nobody ever asked why the gateway/data bus does not work with scaled-out SQL or RabbitMQ an indication that this is a real edge case?

**Comment by mauroservienti** [comment]
> @mauroservienti it still is true for MSMQ. For all the competing consumers transports the problem that @janovesk discusses here existed from the beginning of time.

Oh yes, that's by design with MSMQ.

> @janovesk is the fact that nobody ever asked why the gateway/data bus does not work with scaled-out SQL or RabbitMQ an indication that this is a real edge case?

Good point.

**Comment by mauroservienti** [comment]
> I'm leaning against solution 3, extending the persistence store. It's the only backwards compatible solution I can see ATM.

I agree, given the compatibility requirements I'd favor this one as well.

**Comment by janovesk** [comment]
>@janovesk is the fact that nobody ever asked why the gateway/data bus does not work with scaled-out SQL or RabbitMQ an indication that this is a real edge case?

Either that or it is just way more commonly used for MSMQ. 

Let's say you use a brokered transport. The broker is likely to run on some serious hardware with HA etc. (or you buy it as a service, like Azure Service Bus). You would not have a lot of these, as they are expensive. In fact, I think the most common scenario it to have ONE broker used by everything. Everyone has to have access to the broker. All the necessary firewall openings etc. are in place for endpoints to talk to it. Why would you need the gateway in that scenario? You already have a sharing mechanism: the broker.

When running MSMQ, none of this applies. There is nothing "in the middle" that everybody already has access to. Opening firewall and routing MSMQ over WANS is a pain, so enter the gateway with it simple firewall-busting HTTP requests. 

Either way, we are breaking the gateway with databus for client side scaled-out MSMQ in version 6.

**Comment by mauroservienti** [comment]
I always looked at the Gateway as an anti corruption layer other than a way
to cross a hard boundary, so I don't think that it is super used as its use
cases are somewhat limited.

I think that is reasonable, especially given its ACL, nature that it fully
supports the DataBus even if scaled out, the only thing is that maybe the
priority of this is lower than other things we have in progress or in the
backlog, IMO.

On Fri, Feb 19, 2016, 09:52 Jan Ove Skogheim <notifications@github.com>
wrote:

> @janovesk <https://github.com/janovesk> is the fact that nobody ever
> asked why the gateway/data bus does not work with scaled-out SQL or
> RabbitMQ an indication that this is a real edge case?
>
> Either that or it is just way more commonly used for MSMQ.
>
> Let's say you use a brokered transport. The broker is likely to run on
> some serious hardware with HA etc. (or you buy it as a service, like Azure
> Service Bus). You would not have a lot of these, as they are expensive. In
> fact, I think the most common scenario it to have ONE broker used by
> everything. Everyone has to have access to the broker. All the necessary
> firewall openings etc. are in place for endpoints to talk to it. Why would
> you need the gateway in that scenario? You already have a sharing
> mechanism: the broker.
>
> When running MSMQ, none of this applies. There is nothing "in the middle"
> that everybody already has access to. Opening firewall and routing MSMQ
> over WANS is a pain, so enter the gateway with it simple firewall-busting
> HTTP requests.
>
> Either way, we are breaking the gateway with databus for client side
> scaled-out MSMQ in version 6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.Gateway/issues/20#issuecomment-186120813>
> .
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by janovesk** [comment]
No going to argue that this is the most pressing issue we have, but if we don't fix it we basically break gateway with datbus support for scaled out MSMQ from one major to another.

**Comment by mauroservienti** [comment]
> No going to argue that this is the most pressing issue we have, but if we don't fix it we basically break gateway with datbus support for scaled out MSMQ from one major to another.

I agree, this should be fixed and solution 3 seems to be the mist appropriate

**Comment by mauroservienti** [comment]
@Particular/platform-dev-squad this is missing a proper task force, @janovesk please ping people to set up one.

**Comment by SzymonPobiega** [comment]
I've tried writing proper acceptance tests for callbacks via gateway but realized that scale out does not work completely. The only recommendation would be to run the gateway on a single instance in a scaled-out endpoint.

**Comment by janovesk** [comment]
This is a subtask of https://github.com/Particular/PlatformDevelopment/issues/133 @mauroservienti. Using that as task force.

**Comment by janovesk** [comment]
:( @SzymonPobiega. What exactly is not working when scaling out?

**Comment by SzymonPobiega** [comment]
@janovesk there are ATs in the gateway that verify if you can do callbacks via a gateway. All good, but the test uses a single instance of the client. I wanted to make sure it works in more real-life scenarios where there is more than one instance of the client but realized there is no way I can use gateway when scaled out (which this issue is about;-)

**Comment by janovesk** [comment]
Requested a session with @udidahan to get the business requirements for the gateway before spending more effort on this.

**Comment by janovesk** [comment]
After discussing this on a call we selected to provide simply guidance about how the gateway is designed to run on a single instance, even when you scale out. 

We expect very few people use the combination gw + databus + scale out and if we get reports from customers that this is insufficient, we can readdress this issue later.

**Comment by mikeminutillo** [comment]
@janovesk where is this guidance going to go? In doco? Is there already a PR for it? What is required to close this issue?

**Comment by adamralph** [comment]
> This is a subtask of Particular/PlatformDevelopment#133 @mauroservienti. Using that as task force.

@janovesk can you please copy the list into the issue description, then all our automation, (e.g. pbot pig me) will recognise it.

**Comment by janovesk** [comment]
Closed by https://github.com/Particular/docs.particular.net/pull/1308
