### ISSUE TITLE
Remove maxConcurrency config setting - code only api

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus.Gateway#27]
Same as https://github.com/Particular/NServiceBus/pull/3418, just for the gateway.

Also as requested https://github.com/Particular/NServiceBus.Gateway/pull/26#discussion_r51992026

**Comment by andreasohlund** [comment]
We now have a code first api https://github.com/Particular/NServiceBus.Gateway/blob/develop/src/NServiceBus.Gateway/Settings/GatewaySettings.cs#L121 and all the app.config stuff is going away in the next major so this is no longer relevant
