### ISSUE TITLE
Update to NSB v6

### ISSUE THREAD

**Issue by adamralph** [Particular/NServiceBus.Gateway#39]

**Comment by andreasohlund** [comment]
Not convinced we need to be this strict about the issue rule? in this case it's just a pr to keep the gateway up to date with the evolving core. To me having an issue as well is just noise for this type of things?

I do agree with the we should have issues opened most of the time in general but I think there needs to be some wiggle room?

@Particular/platform-dev-squad thoughts?

**Comment by SimonCropp** [comment]
dicussion is happening on the PR. this is no value
