### ISSUE TITLE
NSB.Gateway 1.0 will not accept messages from NSB 3.x

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Gateway#55]
A V3 endpoint cannot send messages to a Gateway running NSB 5.x and NSB.Gateway 1.0.1.

The V3 client gets `400 Bad Request`.

The V5 server shows this:

> WARN  NServiceBus.Gateway.Channels.Http.HttpChannelReceiver Cannot process HTTP request from [fe80::b061:f586:e59e:6bab%4]:57604. Reason: Invalid CallType 'Submit'. CallTypes supported 'SingleCallSubmit, SingleCallDatabusProperty'.

In V3, the Gateway uses these call types:

    public enum CallType
    {
        Submit,
        Ack,
        DatabusProperty
    }

But in CoreV5/NSB.Gateway 1.0, it seems to have changed drastically:

    public enum CallType
    {
        /// <summary>
        /// Default request type.
        /// </summary>
        SingleCallSubmit,
        /// <summary>
        /// Request type for Databus properties.
        /// </summary>
        SingleCallDatabusProperty
    }

It seems "single call" means that Acks are not required. In V3, it does a `Send`, then sends any data bus properties, and then ends with an `Ack`.

Calling on @johnsimons as you touched Gateway code in V3, otherwise @SimonCropp and @andreasohlund may be the only ones with enough historical perspective on this. (Outside Udi of course.)

Related to [Desk Case](https://nservicebus.desk.com/agent/case/18676).

**Comment by DavidBoike** [comment]
Created a WIP PR in #56 that may be a potential fix, although I don't fully understand the implications.

**Comment by johnsimons** [comment]
@DavidBoike I am back next Monday, can this wait?

**Comment by johnsimons** [comment]
@DavidBoike just a few observations, does it work from v3 -> v4 -> v5 ?

**Comment by DavidBoike** [comment]
@johnsimons Yes I think it can wait. In the meantime, the customer is trying out a NuGet package created from the PR in #56 to see if that works for them.

**Comment by DavidBoike** [comment]
Pinged the customer to find out if the prerelease package worked.

@johnsimons Could you review the PR in #56 and see what you think? It seems like the Ack was designed to say any DataBus stuff was done. Would it perhaps work just fine, as long as you also don't use the DataBus with it?

**Comment by johnsimons** [comment]
@DavidBoike the issue is that a customer needs to update from v3->v4 and the go from v4->v5.

The v4 code was compatible, see https://github.com/Particular/NServiceBus/blob/support-4.7/src/NServiceBus.Core/Gateway/Sending/CallType.cs

**Comment by johnsimons** [comment]
Anyway, yes it looks like you are going the right way, but it is still missing the v3 DatabusProperty

**Comment by DavidBoike** [comment]
Should we even support communication direct from V3 to V5 gateway?

Will be problematic for customer since they have customers using V3 code and want to upgrade their internal stuff. Basically customers may not be likely to upgrade quickly or even ever?

I'll have to dig into that V4 code more. How would you personally feel about reintroducing enum members that were specifically obsoleted?

**Comment by johnsimons** [comment]
> I'll have to dig into that V4 code more. How would you personally feel about reintroducing enum members that were specifically obsoleted?

Well, we supposedly try our best to be wire compat, so in it seems to me that we should do it.
But, given that v3 support has expired a while back, I am not sure.
Sorry!

**Comment by andreasohlund** [comment]
>Well, we supposedly try our best to be wire compat, 

Given that this is gateway to gateway compatibility and you're more likely to update GW's in lockstep since the GW is used within a given "service" I'd say we should just document this? (esp. since we no longer support v3)

**Comment by DavidBoike** [comment]
Found out customer is going to force their clients to upgrade anyway, and given V3 is out of support, closing as won't fix.

Raised https://github.com/Particular/docs.particular.net/issues/1793 to document the version compatibility.
