### ISSUE TITLE
Support-1.0 build is broken

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Gateway#60]
GVT issue as it seems C:\Build\src\packages\NuGetPackager.0.5.5\build\NuGetPackager.targets(6, 5): error MSB4044: The "CreatePackages" task was not given a value for the required parameter "Version". 

https://builds.particular.net/viewLog.html?buildId=188806&tab=buildResultsDiv&buildTypeId=NServiceBusGateway_1Build

**Comment by kbaley** [comment]
Closing. Broken build fixed a while ago.
