### ISSUE TITLE
Change dependency from NServiceBus.DataBus to NServiceBus.ClaimCheck

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus.Gateway#664]
### Describe the suggested improvement

The DataBus API built into NServiceBus is obsolete and has moved to a separate library, `NServiceBus.ClaimCheck`.   The NServiceBus.Gateway library needs to be migrated away from NServiceBus core and to the new library.

**Comment by adamralph** [comment]
@WilliamBZA is the library NServiceBus.ClaimCheck.DataBus or NServiceBus.ClaimCheck?

**Comment by WilliamBZA** [comment]
The package is NServiceBus.ClaimCheck.
