### ISSUE TITLE
Missing MultiSite profile support

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.Gateway#7]
The core used to support `NServiceBus.MultiSite` as a profile. Since that's now obsoleted in NSB v5, what's the equivalent profile in NServiceBus.Gateway?

- [ ] Fix the obsolete message 
- [ ] Update doco and remove multisite from it

**Comment by johnsimons** [comment]
No users so far asked for it, if there is a requirement for it, we reopen this issue
