### ISSUE TITLE
Gateway should look at Content-Encoding header

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Gateway#8]
Raised by @johnsimons
Migrated from by https://github.com/Particular/NServiceBus/issues/1381

When a http request is received, an MD5 is calculated against the body payload, but by default it uses UTF8.

Instead it should look at the `Content-Encoding` header and then use the correct encoder to retrieve the payload

**Comment by johnsimons** [comment]
This is actually only used if the message body is transmitted via querystring, which is unlikely and that way the encoding used is fine to be decoded using utf8.
The Content-Encoding header only applies for payload not querystyring.

So we are fine :)
