### ISSUE TITLE
Unable to receive on multiple channels

### ISSUE THREAD

**Issue by welshdave** [Particular/NServiceBus.Gateway#98]
While attempting to set up a gateway listening on a wildcard address I found that the gateway currently doesn't listen on multiple addresses. Instead, the last configured receive channel is used. 

If you configure a wildcard channel last, then you get an error (because you can't use a wildcard receive channel as the default channel).

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus.Gateway/issues/103
